apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 31001 # port of the service exposed for pod
    nodePort: 31002 #node port
    targetPort: nodejs-port #actual port of container
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort  
